### ISSUE TITLE
"grunt" command freezes at running "watch" task

### ISSUE THREAD

**Issue by r01010010** [flowxo/flowxo-services-trello-example#1]
![grunt_freeze](https://cloud.githubusercontent.com/assets/698953/7727192/85781d2a-ff07-11e4-96ae-041a220b33cd.png)

**Comment by fiznool** [comment]
This is expected behaviour.

The default `grunt` task ends with a watch task, which watches for changes in the filesystem and then re-runs the tests. You end this task with `Ctrl-C`.

https://github.com/gruntjs/grunt-contrib-watch
